version: "3.9"

services:
  notebook:
    container_name: 24-787-term-project
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 10000:8888
    volumes:
      - ./:/home/notebook
